name: auth-service CI/CD

on:
  push:
    branches: [main]
    paths:
      - "services/auth-service/**"
      - "docker/Dockerfile.auth"
      - ".github/workflows/auth-service.yml"
      - ".github/workflows/_reusable-service-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "services/auth-service/**"
      - "docker/Dockerfile.auth"
      - ".github/workflows/auth-service.yml"
      - ".github/workflows/_reusable-service-ci.yml"

jobs:
  ci:
    uses: ./.github/workflows/_reusable-service-ci.yml
    with:
      service_name: auth-service
      service_path: services/auth-service
      dockerfile: docker/Dockerfile.auth
      language: go
      port: "8001"
      gitops_path: gitops/auth-service/deployment.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
# dispara pipeline inicial
