name: flag-service CI/CD

on:
  push:
    branches: [main]
    paths:
      - "services/flag-service/**"
      - "docker/Dockerfile.flag"
      - ".github/workflows/flag-service.yml"
      - ".github/workflows/_reusable-service-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "services/flag-service/**"
      - "docker/Dockerfile.flag"
      - ".github/workflows/flag-service.yml"
      - ".github/workflows/_reusable-service-ci.yml"

jobs:
  ci:
    uses: ./.github/workflows/_reusable-service-ci.yml
    with:
      service_name: flag-service
      service_path: services/flag-service
      dockerfile: docker/Dockerfile.flag
      language: python
      port: "8002"
      gitops_path: gitops/flag-service/deployment.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
